config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :products
  root 'products#index'
  resource :cart, only: [:update, :show, :destroy]
  
  resources :orders, only: [:index, :create]

end

app/models/cart.rb
class Cart

  def initialize
    @cart = []
  end

  public

  def add product
    @cart << product
  end

  def delete product
    el_index = @cart.find_index do |el|
      el.id == product.id
    end
    
    @cart.delete_at el_index
  end

  def show_price
    @cart.reduce 0 do |sum, el|
      sum += el.price
    end
  end

  def all
    @cart
  end

  def delete_all
    @cart = []
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :products, through: :order_products 
  has_many :order_products
  
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base

  belongs_to :order
  belongs_to :product
  
end

app/models/product.rb
class Product < ActiveRecord::Base

  #scope :cheap => { where('price < 2') },
      # :cheaper_then => (p) { where('price < p') }   

  has_many :orders, through: :order_products
  has_many :order_products

  mount_uploader :image, ProductUploader

  validates :name,
            presence: true,
            length: { minimum: 2 }

  validates :price,
            presence: true,
            numericality: true

  def convert_to_ua
    price * 8
  end

end
#use scope like Product.cheap

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  
  def cart
    unless session[:cart]
      session[:cart] = Cart.new
    end

    session[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def update
    if params[:type] == 'delete'
      product = Product.find(params[:id])
      cart.delete product
    else
      cart.add Product.find(params[:id])
    end

    redirect_to request.referer
  end

  def show
    @products = cart.all
    @total_price = cart.show_price
  end

  def destroy
    cart.delete_all
    redirect_to request.referer
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def create
    return redirect_to(cart_path) unless cart

    order = Order.new(total_price: cart.show_price)
    order.products = cart.all

    if order.products.size > 0 && order.save
      cart.delete_all
      redirect_to orders_path
    else
      redirect_to cart_index_path
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!,
                :except => [:index, :show]

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 2)
    # @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def destroy
    Product.find(params[:id]).destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :image)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1> Cart </h1>

<% @products.each do |product| %>
    <div class="product">
        <%= link_to product.name, product_path(product) %>
        <span>$<%= product.price %></span>
        <span><%= product.description %></span>
        <%= link_to 'Remove from cart', cart_path(product), method: :delete %>
    </div>
<% end %>

<br />

<%= link_to 'Clear cart', cart_path({ :id => 'all' }), method: :delete %> |
<%= link_to 'Home', products_path %> |
<%= link_to 'Buy', orders_path, method: :post %>

app/views/carts/show.html.erb
<h1> Cart </h1>

<% @products.each do |product| %>
    <div class="product">
        <%= link_to product.name, product_path(product) %>
        <span>$<%= product.price %></span>
        <span><%= product.description %></span>
        <%= link_to 'Remove from cart', cart_path(:id => product.id, :type => 'delete'), method: :patch %>
    </div>
<% end %>

<br />

<%= link_to 'Clear cart', cart_path, method: :delete %> |
<%= link_to 'Home', products_path %> |
<%= link_to 'Buy', orders_path, method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div>
        <% if user_signed_in? %>
            <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to 'Sign In', new_user_session_path %> |
            <%= link_to 'Register', new_user_registration_path %>
        <% end %>
    </div>
<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>

<% @orders.each do |order| %>
    <% order.products.each do |product| %>
        <div>
            <%= link_to product.name, product_path(product) %>
            <span>$<%= product.price %></span>
        </div>
    <% end %>
    Total price: $<%= order.total_price %>
    <br />
<% end %>

<%= link_to 'Home', products_path %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :price %><br>
        <%= f.text_field :price %>
    </p>

    <p>
        <%= f.label :description, multiple: true %><br>
        <%= f.text_field :description %>
    </p>

    <%= f.file_field :image %>

    <%= f.submit %>
<% end %>

<% if @product.errors.any? %>
    <h3>Error!</h3>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1> Products </h1>

<% @products.each do |product| %>
    <div class="product">
        <%= link_to product.name, product_path(product) %>
        <span>$<%= product.price %></span>
        <span><%= product.description %></span>
        <%= link_to 'Add to cart', cart_path(:id => product.id), method: :patch %>
    </div>
<% end %>

<br />

<%= will_paginate @products %>


<%= link_to 'Add product', new_product_path %> |
<%= link_to 'Show cart', cart_path %> |
<%= link_to 'Show orders', orders_path %>

app/views/products/new.html.erb
<h1>Add product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<div>Price: $<%= @product.price %></div>

<% if @product.description.size > 0 %>
    <div>Description: <%= @product.description %></div>
<% end %>

<%= image_tag(@product.image) %>

<%= link_to 'Edit', edit_product_path %> | 
<%= link_to 'Destroy', product_path(@product), method: :delete %> | 
<%= link_to 'Back', products_path %> 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>